### PR TITLE
Update remarks command

### LINKED ISSUE #91: Create a remark class
Which stores the remark as a string and is supported by the person class and XmlAdaptedPerson class.

### PR DESCRIPTION
**Pull request by nhs-work**
Fixes #91 , #92 , #93

### CODE REVIEW

**Review by cxingkai — COMMENTED** [review]
Nice job, but I think that the isValidRemark test in RemarkTest could be better named

**Comment by Kyholmes** [comment]
good job on updating UI test

**Comment by Kyholmes** [comment]
good job on updating test for UI

**Comment by nhs-work** [comment]
The isValidRemark test in RemarkTest follows the naming conventions of the other classes related to the Person class. We can consider renaming all of them should there be a better name. But for now, I will be leaving it as it is.

**Comment by ktingit** [comment]
Looks good to me

**Pull request merged**
